name = "Simple Style"
license = "MIT"
licenselink = "https://github.com/yanlinlin82/simple-style/blob/master/LICENSE"
description = "Linlin Yan's very simple style."
homepage = "https://github.com/yanlinlin82/simple-style/"
tags = [ "simple", "blog", "white" ]
features = [ "simple", "white" ]
min_version = "0.61.0"

[author]
name = "Linlin Yan"
homepage = "http://yanlinlin.cn/"
