Name = ""

# Supports markdown
About = ""

Email = ""

# Add the filename with file extension.
Resume = ""

# Sets the number of posts to display on the front page
PostLimit = 4

GoatCounterCode = ""

[[profiles]]
name = "GitHub"
url = ""

[[profiles]]
name = "Twitter"
url = ""

[[profiles]]
name = "Goodreads"
url = ""

[[profiles]]
name = "LinkedIn"
url = ""
