baseURL = "https://example.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Hugo Huginn Theme"
theme = "huginn"

[Params]
  avatar = "img/avatar.png"
  sitesubtitle = "Blog subtitle"
  footer = "Custom footer"  # Custom footer in Markdown
  # isso_server = ""  # URL of Isso server

  # [Params.staticman]
  #   endpoint =  "" # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
  #   gitProvider = "gitlab"  # either "github" or "gitlab"
  #   repo = "user/repo"  # your GitHub/GitLab repository
  #   branch = "master"  # branch on which you want to receive comments

  #   # # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
  #   # [Params.staticman.reCaptcha]
  #   #   siteKey = ""  # Use your OWN site key, you need to apply for one on Google
  #   #   secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

