baseURL = "/"
languageCode = "zh-cmn-Hant"
title = "Bingo"
theme = "hugo-bingo"
themesDir = "../.."

disableHugoGeneratorInject = true
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
googleAnalytics = "UA-123-45"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

[permalinks]
  post = "/posts/:slug/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20

[params]
  dateFormat = "2006-01-02"
  mainSections = ["post"]

  [params.gravatar]
    email = "hugo@example.com"

  [[params.social]]
    name = "github"
    url = "https://github.com/example"
    weight = 10

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/example"
    weight = 30

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/story/example"
    weight = 40

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/example"
    weight = 20
