baseURL = "https://example.com"
languageCode = "en-us"
hasCJKLanguage = true
disqusShortname = ""
googleAnalytics = ""
title = "Your site title"
copyright = ""

[taxonomies]
  tag = "tags"

[params]
  googleAutoAds = ""
  avatar = "https://openclipart.org/download/103855/tux.svg"
  author = "Your name"
  info = "Any info about you"

[[menu.main]]
  name = "Github"
  weight = 1
  url = "https://github.com/gonnux"

[[menu.main]]
  name = "Website"
  weight = 2
  url = "https://gonnux.com"

[[menu.main]]
  name = "*Apps*"
  weight = 3
  url = "/apps"

[[menu.main]]
  name = "README"
  weight = 3
  url = "/README"


[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/gonnux"

[[params.social]]
  name = "Gitlab"
  weight = 2
  url = "https://gitlab.com/gonnux"

[[params.social]]
  name = "Website"
  weight = 3
  url = "https://gonnux.com"
